// test_gguf_kquant.c - Verify the K-quant dequantizers (Q2_K..Q6_K) against
// the authoritative llama.cpp `gguf` package reference.
//
// The fixture (tests/kquant_fixture.bin) is generated by
// tests/gen_kquant_fixture.py: for each type it holds random raw quantized
// bytes and the reference dequantized floats. boat_gguf_dequantize must
// reproduce them exactly.

#include <boat/format/gguf.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

static int g_fail = 0;
#define CHECK(cond, msg)                                                      \
    do {                                                                      \
        if (!(cond)) {                                                        \
            printf("FAIL: %s (%s:%d)\n", msg, __FILE__, __LINE__);            \
            g_fail++;                                                         \
        }                                                                     \
    } while (0)

static uint32_t rd_u32(const uint8_t* p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static uint64_t rd_u64(const uint8_t* p) {
    uint64_t v = 0;
    for (int i = 0; i < 8; i++) v |= (uint64_t)p[i] << (8 * i);
    return v;
}

int main(void) {
    // Locate the fixture: ctest runs from the build dir (fixture copied by
    // CMake) or from the repo root (make test) / the tests/unit dir.
    const char* cand[] = {"kquant_fixture.bin", "tests/unit/kquant_fixture.bin",
                          "../../tests/unit/kquant_fixture.bin", "../kquant_fixture.bin"};
    FILE* f = NULL;
    const char* used = NULL;
    for (size_t i = 0; i < sizeof(cand) / sizeof(cand[0]); i++) {
        f = fopen(cand[i], "rb");
        if (f) {
            used = cand[i];
            break;
        }
    }
    CHECK(f != NULL, "open fixture");
    if (!f) return 1;
    (void)used;
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    rewind(f);
    uint8_t* buf = (uint8_t*)malloc((size_t)sz);
    if (fread(buf, 1, (size_t)sz, f) != (size_t)sz) return 1;
    fclose(f);

    const char* names[] = {"Q2_K", "Q3_K", "Q4_K", "Q5_K", "Q6_K"};
    uint32_t n_types = rd_u32(buf);
    CHECK(n_types == 5, "fixture has 5 types");
    const uint8_t* p = buf + 4;

    for (uint32_t t = 0; t < n_types; t++) {
        uint32_t type = rd_u32(p);
        p += 4;
        uint64_t n = rd_u64(p);
        p += 8;
        uint64_t nbytes = rd_u64(p);
        p += 8;
        const uint8_t* raw = p;
        p += nbytes;
        const float* expected = (const float*)p;
        p += n * 4;

        float* got = (float*)malloc((size_t)n * sizeof(float));
        CHECK(boat_gguf_dequantize(raw, (size_t)nbytes, (int)type, got, (size_t)n),
              "dequantize succeeds");
        double max_err = 0.0;
        for (uint64_t i = 0; i < n; i++) {
            double e = fabs((double)got[i] - (double)expected[i]);
            if (e > max_err) max_err = e;
        }
        char msg[64];
        snprintf(msg, sizeof(msg), "%s dequant matches reference (max err %.6g)", names[t],
                 max_err);
        CHECK(max_err < 1e-3, msg);
        printf("  %s: n=%llu bytes=%llu max_err=%.6g\n", names[t], (unsigned long long)n,
               (unsigned long long)nbytes, max_err);
        free(got);
    }
    free(buf);
    if (g_fail) {
        printf("%d test(s) FAILED\n", g_fail);
        return 1;
    }
    printf("All GGUF K-quant dequant tests passed.\n");
    return 0;
}
